
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%% Change the positin of PSU, DO NOT consider the throughput of PSU %%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clc; clear variables; clf;
close all;
disp('Bismillah: Code generated by Khalid Ibrahim');

N = 5;          % Total No. of Channels
% H = N;           % Total no of PUs
% SNRdb = [0:10:1000];
SNRdb = [0 10 13 14 15 16 17 18 19 20 21:1000];
SNRp1 = 10.^ (SNRdb./10);
SNRp =  SNRp1(1:N);

bandwidth = 1;
capacity_var = bandwidth .* log2 (1+SNRp) ;     % Channel Capacity in bps
% successful_gain = 1;

%% Without PSU
R = (1:500)*5;     % Discrete data rates
R = R(1:N);        % Discrete data rates for N users
r = R/sum(R);      % Probability of each user with reference to its data rate

y = 1;
RunningVector = 0:0.1:1;
for b = RunningVector % b is a running variable from 0:0.1:1
    %     p = (1/H) .* ones(H,1); % flat probability for all SUs
    p = r';
    %     Utility = (H * successful_gain) - sum (p * (successful_gain  + jamming_gain));
    UwithCapacity1 = sum(capacity_var)  - (capacity_var * p );
    UwithCapacity22(1,y) = UwithCapacity1;
%     throughput(1,y) = (1-p)' * capacity_var';
    y = y + 1;
end
Legend(1)={'Without PSU'};

%% With PSU
R = (1:500)*5;      % Discrete data rates
R = R(1:N);         % Discrete data rates for N users
% Rp = [1:500]*5 ;
Rp = (1:3500)*1 ;    % Probability of PSU with reference to its data rate

n = 1; % Location of PSU
z = 1;

for rp = Rp
    R(n) = rp;
    rpp(z) = R(n)/sum(R); 
    r = R/ sum(R);
    sum(r);
    r(n);
    UwithCapacity2(1,z) = r(n) *(sum(capacity_var(2:end))  - capacity_var(2:end) * r(2:end)') ;
    z=z+1;
end
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(1)
plot(Rp,UwithCapacity2,'b','linewidth',1.5);
% plot(UwithCapacity2,'r','linewidth',1.5,'Marker','s');
hold on;
grid on;
Legend(1)={'With PSU'};    

figure(1)
plot(Rp,UwithCapacity22(1:size(rpp)),'g','linewidth',0.5,'Marker','s');
% plot(UwithCapacity22(1:size(rpp)),'b','linewidth',1.5,'Marker','s');
Legend(2)={'Without PSU'};

% title(['Do not consider the throughput of PSU. | N = ',num2str(N)]);
xlabel('Data Rate of PSU (bps)');
ylabel('Bandwidth efficiency (bps/Hz)');
legend(Legend)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure(2)
plot(rpp,UwithCapacity2,'b','linewidth',1.5);
% plot(UwithCapacity2,'r','linewidth',1.5,'Marker','s');
hold on;
grid on;
Legend(1)={'With PSU'};    

figure(2)
plot(rpp,UwithCapacity22(1:size(rpp)),'g','linewidth',0.5,'Marker','s');
% plot(UwithCapacity22(1:size(rpp)),'b','linewidth',1.5,'Marker','s');
Legend(2)={'Without PSU'};
% xlim([])



% title(['Do not consider the throughput of PSU. | N = ',num2str(N)]);
xlabel('\delta ','FontSize',15,'FontWeight', 'bold');
ylabel('Bandwidth efficiency (bps/Hz)');
legend(Legend)


